name: Build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build shadowJar reobfJar
    - name: artifact
      uses: actions/upload-artifact@v3   
      with:
        name: RivalsAPI-${{ github.run_number }}
        path: build/libs/RivalsAPI-${{ github.run_number }}.jar
    - name: Tag and create release
      uses: softprops/action-gh-release@v1
      with:
        body: "${{ join(github.event.commits.*.message, '<br>') }}"
        tag_name: Build-v${{ github.run_number }}
        files: build/libs/RivalsAPI-${{ github.run_number }}.jar
